using System;
using System.Collections.Generic;
using System.Text;

namespace WorkflowCore.Services.ApiServices
{
    public class AuthorizationService: IAuthorizationService
    {
        public string AccessToken { get; set; } =
            "eyJhbGciOiJSUzI1NiIsImtpZCI6ImlhWlR2bE9PQWhUTTBkdVJBYV9yMFEiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1NzQyMzU4NDMsImV4cCI6MTU3NDIzOTQ0MywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzODciLCJhdWQiOiJVc2VyQXBpIiwiY2xpZW50X2lkIjoiZGV2LWdhdGV3YXktYXBpIiwic3ViIjoiNUJFODYzNTktMDczQy00MzRCLUFEMkQtQTM5MzIyMjJEQUJFIiwiYXV0aF90aW1lIjoxNTc0MjM1ODM3LCJpZHAiOiJsb2NhbCIsInJvbGUiOiJhZG1pbiIsInNjb3BlIjpbInVzZXJfcmVhZF9vbmx5Il0sImFtciI6WyJwd2QiXX0.yyq8yr1VgyfIMsOM3vwLsZx4pTf4x0Ihj6M0JPikon93zJAxVQzYQMHt6FKKMVybktVZgPyxLmNV0rLhliY-In1KcUBF88HQAtr0gXlLKyrZIOVfmz_C98CXEc_AGCHaDDnecvxHmQXHTUuF2YGSwVqkbbljmnsl19g_3xjNIQrpkH1VjtkUUCLxipALtZZjitl-_eMveAiLbF0-I8p2v2ncdySLSeVvgo1ozRA88Rf1kcgVpDQttaA94PxlrQ8vhIGQHKUV8RS5IoxK8x_JHu6FWVTmEGuPWp68aqV_XyvqCcOPh2f-eozBmdi_T_0tA2mzHVmifv7qWFy5PRYpVw";
    }
}
